# Company Analyzer Configuration Example
# This file demonstrates various configuration options available

# Core processing settings
chunk_size: 3000
default_csv_file: "my_data.csv"
min_company_name_length: 3
max_company_name_length: 100
filter_type: "folders"  # Options: 'all', 'folders', 'files'

# Detection and analysis settings
confidence_threshold: 0.5
strict_mode: true
enable_enhanced_detection: true
enable_caching: true
enable_parallel_processing: false

# Logging configuration
log_level: "DEBUG"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
log_file: "debug_analyzer.log"
log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Output settings
max_search_results: 20
max_summary_companies: 100
output_directory: "custom_output"
output_formats:
  - "json"
  - "csv"
  - "xlsx"

# NLP settings
spacy_model: "en_core_web_sm"

# Known companies (will be added to the default list)
known_companies:
  - "Accent Group"
  - "AGL"
  - "My Custom Company Inc"
  - "Another Business LLC"
  - "Tech Startup Co"

# Additional exclusion patterns (will be added to defaults)
exclude_patterns:
  - "^TEST_.*"        # Test files
  - ".*_BACKUP$"      # Backup files
  - "^TEMP_.*"        # Temporary files
  - ".*_OLD$"         # Old files

# Additional company indicator patterns
company_indicators:
  - "\\b(startup|venture|capital)\\b"
  - "\\b(fintech|biotech|cleantech)\\b"

# CSV column mappings (customize for your CSV structure)
csv_columns:
  name: "Company Name"
  path: "File Path"
  modified_by: "Last Modified By"
  item_type: "Type"
  file_size: "Size"
  modified: "Date Modified"

# Performance settings
max_workers: 6
cache_size: 2000 