# ==========================================
# LOCAL CONFIGURATION FOR COMPANY ANALYZER
# ==========================================
# This config focuses on LOCAL analysis only - no AI or online features

# ==========================================
# WHAT TO ANALYZE (THIS IS THE KEY SETTING!)
# ==========================================
filter_type: "all"
# Options:
#   "all"     - Analyze both files and folders
#   "folders" - Only analyze folders  
#   "files"   - Only analyze files

# ==========================================
# BASIC PROCESSING SETTINGS
# ==========================================
chunk_size: 5000
# How many rows to process at once (larger = faster but more memory)

confidence_threshold: 0.3
# How confident to be about company detection (0.0-1.0, lower = more results)

# ==========================================
# COMPANY NAME RULES
# ==========================================
min_company_name_length: 2
max_company_name_length: 50
# Company names must be between these lengths

# ==========================================
# OUTPUT SETTINGS
# ==========================================
output_formats:
  - "json"
  - "csv"
  - "txt"
# Which file formats to save results in

max_search_results: 10
# Maximum results to show in searches

max_summary_companies: 50
# Maximum companies to show in summary

# ==========================================
# CSV FILE STRUCTURE
# ==========================================
# Tell the analyzer which columns in your CSV contain what data
csv_columns:
  name: "Name"                    # Column with file/folder names
  path: "Path"                    # Column with file paths
  modified_by: "Modified By"      # Column with who modified it
  item_type: "Item Type"          # Column with "File" or "Folder"
  file_size: "File Size"          # Column with file sizes
  modified: "Modified"            # Column with modification dates

# Example: if your CSV has "Company Name" column, change "Name" to "Company Name"

# ==========================================
# OPTIONAL: ADD KNOWN COMPANIES
# ==========================================
# Companies you know exist - helps improve detection accuracy
known_companies:
  - "Microsoft Corporation"
  - "Apple Inc"
  - "Google LLC"
  - "Amazon Web Services"

# ==========================================
# TECHNICAL SETTINGS (usually don't need to change)
# ==========================================
enable_enhanced_detection: true
# Use advanced NLP for better company detection

enable_caching: true
# Speed up processing by caching results

log_level: "INFO"
# How much logging: DEBUG, INFO, WARNING, ERROR 